name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'hello world' > output.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'your-artifact-name'
          path: 'output.txt'

  approve-develop:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Request approval for develop deployment
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Requesting approval for develop deployment..."
          ISSUE_NUMBER=$(gh issue list --state open --label deployment-requested --json number --jq '.[0].number')
          gh issue comment $ISSUE_NUMBER -b "Deployment Approval requested for develop. Comment 'Approved' to proceed with deployment."
          echo "Approval requested."

      - name: Wait for approval
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Waiting for approval..."
          ISSUE_NUMBER=$(gh issue list --state open --label deployment-requested --json number --jq '.[0].number')
          while [[ "$(gh issue view $ISSUE_NUMBER --json state --jq '.state')" != "closed" ]]; do
            sleep 30
          done

  deploy-develop:
    needs: approve-develop
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to develop
        run: echo "Deploying to develop"
