name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Simulate a Build
        run: echo 'hello world' > output.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'your-artifact-name'
          path: 'output.txt'

  approve-develop:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Request approval for develop deployment
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          ENVIRONMENT: develop
          RUNNUMBER: ${{ github.run_number }}
        with:
          filename: .github/deployment-approval.md
      - name: Wait for approval
        run: |
          echo "Waiting for approval..."
          while [[ "$(gh issue view {{ steps.request-approval.outputs.issue_number }} --json state --jq '.state')" != "closed" ]]; do
            sleep 30
          done

  deploy-develop:
    needs: approve-develop
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to develop
        run: echo "Deploying to develop"

  approve-uat:
    needs: deploy-develop
    runs-on: ubuntu-latest
    steps:
      - name: Request approval for uat deployment
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          ENVIRONMENT: uat
          RUNNUMBER: ${{ github.run_number }}
        with:
          filename: .github/deployment-approval.md
      - name: Wait for approval
        run: |
          echo "Waiting for approval..."
          while [[ "$(gh issue view {{ steps.request-approval.outputs.issue_number }} --json state --jq '.state')" != "closed" ]]; do
            sleep 30
          done

  deploy-uat:
    needs: approve-uat
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to uat
        run: echo "Deploying to uat"

  approve-hml:
    needs: deploy-uat
    runs-on: ubuntu-latest
    steps:
      - name: Request approval for hml deployment
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          ENVIRONMENT: hml
          RUNNUMBER: ${{ github.run_number }}
        with:
          filename: .github/deployment-approval.md
      - name: Wait for approval
        run: |
          echo "Waiting for approval..."
          while [[ "$(gh issue view {{ steps.request-approval.outputs.issue_number }} --json state --jq '.state')" != "closed" ]]; do
            sleep 30
          done

  deploy-hml:
    needs: approve-hml
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to hml
        run: echo "Deploying to hml"

  approve-prd:
    needs: deploy-hml
    runs-on: ubuntu-latest
    steps:
      - name: Request approval for prd deployment
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          ENVIRONMENT: prd
          RUNNUMBER: ${{ github.run_number }}
        with:
          filename: .github/deployment-approval.md
      - name: Wait for approval
        run: |
          echo "Waiting for approval..."
          while [[ "$(gh issue view {{ steps.request-approval.outputs.issue_number }} --json state --jq '.state')" != "closed" ]]; do
            sleep 30
          done

  deploy-prd:
    needs: approve-prd
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prd
        run: echo "Deploying to prd"
